import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Finding = { ruleId: string; status: string; severity: string; message: string; recommendation: string; evidence: { selector?: string; element?: string; message: string }[] };
type Result = { id: string; status: string; url: string; error?: string; summary?: { passed: number; failed: number; warnings: number; manual: number; errors: number; automatedPassRate: number | null }; ruleResults?: Finding[]; limitations: string[] };
const api = import.meta.env.VITE_API_URL ?? (import.meta.env.DEV ? 'http://localhost:3001' : '');

function App() {
  const [url, setUrl] = useState(''); const [scan, setScan] = useState<Result>(); const [busy, setBusy] = useState(false); const [selected, setSelected] = useState<Finding>();
  const start = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setScan(undefined); const response = await fetch(api + '/api/scans', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ url }) }); const body = await response.json(); if (!response.ok) { setScan({ id: '', status: 'error', url, limitations: [], error: body.error }); setBusy(false); return; } setScan(body); };
  useEffect(() => { if (!scan || !['queued', 'running'].includes(scan.status)) return; const timer = setInterval(async () => { const response = await fetch(api + '/api/scans/' + scan.id); const body = await response.json(); setScan(body); if (!['queued', 'running'].includes(body.status)) setBusy(false); }, 1000); return () => clearInterval(timer); }, [scan?.id, scan?.status]);
  return <main><header><span className="mark">G</span><div><h1>GIGW Compliance Checker</h1><p>Developer-oriented automated assessment for Indian government websites</p></div></header><section className="hero"><h2>Assess a website</h2><form onSubmit={start}><label htmlFor="url">Website URL</label><div className="input"><input id="url" required type="url" placeholder="https://example.gov.in" value={url} onChange={event => setUrl(event.target.value)} /><button disabled={busy}>{busy ? 'Scanning…' : 'Scan website'}</button></div></form><p className="disclaimer">Automated assessment — not an official GIGW/STQC certification.</p></section>{scan?.error && <p className="error">{scan.error}</p>}{scan?.summary && <><section className="score"><div><small>Automated technical checks score</small><strong>{scan.summary.automatedPassRate ?? '—'}{scan.summary.automatedPassRate !== null && '%'}</strong><span>Passed ÷ (Passed + Failed); includes GIGW subset, axe, and generic checks</span></div>{[['Passed', scan.summary.passed], ['Failed', scan.summary.failed], ['Warnings', scan.summary.warnings], ['Manual review', scan.summary.manual]].map(([label, value]) => <div className="metric" key={String(label)}><b>{value}</b><span>{label}</span></div>)}</section><section><h2>Findings</h2><p className="muted">Target: {scan.url}</p><div className="tablewrap"><table><thead><tr><th>Rule</th><th>Status</th><th>Severity</th><th>Description</th><th>Recommendation</th></tr></thead><tbody>{scan.ruleResults?.map(finding => <tr key={finding.ruleId} onClick={() => setSelected(finding)}><td>{finding.ruleId}</td><td><span className={'badge ' + finding.status}>{finding.status}</span></td><td>{finding.severity}</td><td>{finding.message}</td><td>{finding.recommendation}</td></tr>)}</tbody></table></div></section><section className="limits"><h2>Manual verification & limitations</h2><ul>{scan.limitations.map(item => <li key={item}>{item}</li>)}</ul></section>{selected && <aside role="dialog" aria-label="Finding details"><button onClick={() => setSelected(undefined)}>Close</button><h2>{selected.ruleId}</h2><p>{selected.message}</p><h3>Evidence</h3>{selected.evidence.map((evidence, index) => <div className="evidence" key={index}><code>{evidence.selector}</code><p>{evidence.message}</p><pre>{evidence.element}</pre></div>)}</aside>}</>}</main>;
}
createRoot(document.getElementById('root')!).render(<App />);
