import { chromium, type Browser } from 'playwright';
import axe from 'axe-core';
import { runRules } from '@gigw/rules';
import type { ScanResult, RuleResult, AuditContext } from '@gigw/shared';
import { validateTarget } from './security.js';
import { extractionScript } from './extract.js';
let browser:Browser|undefined;
const timeout=Number(process.env.SCAN_TIMEOUT||30000);
async function getBrowser(){return browser??=await chromium.launch({headless:true});}
const quality=(c:AuditContext):RuleResult[]=>{const r=(id:string,status:RuleResult['status'],severity:RuleResult['severity'],message:string,recommendation:string,evidence:RuleResult['evidence']=[])=>({ruleId:id,status,severity,message,recommendation,evidence}); const d=c.document, duplicate=d.ids.filter((x,i,a)=>a.indexOf(x)!==i); return [
r('QUALITY-DUPLICATE-ID',duplicate.length?'FAIL':'PASS','HIGH',duplicate.length?`Duplicate IDs: ${[...new Set(duplicate)].join(', ')}`:'No duplicate IDs detected.','Use unique id values.',duplicate.map(x=>({url:c.url,selector:'#'+x,element:'',message:'Duplicate id.'}))),
r('QUALITY-META-DESCRIPTION',d.metaDescription?'PASS':'WARNING','LOW',d.metaDescription?'Meta description is present.':'Meta description is absent.','Add a concise meta description.'),r('QUALITY-VIEWPORT',d.viewport?'PASS':'WARNING','MEDIUM',d.viewport?'Viewport meta tag is present.':'Viewport meta tag is absent.','Add a responsive viewport meta tag.'),r('QUALITY-IFRAME-TITLE',d.iframes.every(x=>x.title)?'PASS':'FAIL','MEDIUM',d.iframes.every(x=>x.title)?'All iframes have titles.':'One or more iframes have no title.','Give every iframe a meaningful title.',d.iframes.filter(x=>!x.title).map(x=>({url:c.url,selector:x.selector,element:x.html,message:'Iframe title missing.'}))),
r('QUALITY-PDF-MANUAL',d.pdfLinks.length?'MANUAL':'NOT_APPLICABLE','INFO',d.pdfLinks.length?`${d.pdfLinks.length} PDF link(s) detected; document accessibility needs manual verification.`:'No PDF links detected.','Review each PDF using an accessible-PDF testing process.'),r('SECURITY-HTTPS',c.url.startsWith('https:')?'PASS':'WARNING','HIGH',c.url.startsWith('https:')?'Target uses HTTPS.':'Target does not use HTTPS.','Serve the website over HTTPS.'),r('SECURITY-HEADERS', ['content-security-policy','x-content-type-options','referrer-policy'].every(h=>c.headers[h])?'PASS':'WARNING','MEDIUM','Security headers were evaluated.','Configure CSP, X-Content-Type-Options and Referrer-Policy as appropriate.')];};
export async function scan(urlInput:string):Promise<ScanResult>{const id=crypto.randomUUID(),createdAt=new Date().toISOString();try{const url=await validateTarget(urlInput),b=await getBrowser(),ctx=await b.newContext({ignoreHTTPSErrors:false,javaScriptEnabled:true,viewport:{width:1440,height:900}}),page=await ctx.newPage();page.setDefaultTimeout(timeout);const errors:string[]=[];page.on('console',m=>m.type()==='error'&&errors.push(m.text()));const response=await page.goto(url,{waitUntil:'networkidle',timeout});if(!response)throw new Error('No HTTP response received.');const html=await page.content();const document=await page.evaluate(extractionScript) as AuditContext['document'];await page.addScriptTag({content:axe.source});const axeResults=await page.evaluate(async()=>await (window as any).axe.run(document,{resultTypes:['violations','incomplete','passes']}));const headers=Object.fromEntries(Object.entries(response.headers()).map(([k,v])=>[k.toLowerCase(),v]));const context:AuditContext={url:page.url(),html,document,headers,status:response.status()};const ruleResults=[...await runRules(context),...quality(context)];for(const v of axeResults.violations){ruleResults.push({ruleId:`AXE-${v.id}`,status:'FAIL',severity:(v.impact||'medium').toUpperCase() as RuleResult['severity'],message:v.help,recommendation:v.helpUrl,evidence:v.nodes.map((n:any)=>({url:page.url(),selector:n.target.join(', '),element:n.html,message:n.failureSummary||v.description}))});}await ctx.close();const counts={passed:0,failed:0,warnings:0,manual:0,errors:0};for(const x of ruleResults){if(x.status==='PASS')counts.passed++;if(x.status==='FAIL')counts.failed++;if(x.status==='WARNING')counts.warnings++;if(x.status==='MANUAL')counts.manual++;if(x.status==='ERROR')counts.errors++;}return {id,status:'complete',url,createdAt,completedAt:new Date().toISOString(),summary:{...counts,automatedPassRate:counts.passed+counts.failed?Math.round(counts.passed/(counts.passed+counts.failed)*100):null},ruleResults,axe:axeResults,limitations:['Automated assessment — not an official GIGW/STQC certification.','Keyboard interaction, visual focus, content correctness and policy/governance evidence require human review.',...errors.map(x=>'Console error: '+x)]};}catch(e){return {id,status:'error',url:urlInput,createdAt,limitations:['No assessment was completed.'],error:e instanceof Error?e.message:'Unknown scan error'};}}
